Enhance db size metrics to support multiple databases
codenotary/immudb pull request #756
Opened 2021-05-14 16:57 UTC by padurean

The old metric `immudb_db_size_bytes` which was only reporting the size of the default db has been removed and another one has been added instead - **`immudb_db_size_KB`** which supports multiple databases.

⚠️  The metric's values are now in **kilobytes**. It's value is computed so that it would be identical with the output of the `du -ks` Linux command (i.e. it is the size **on disk**).

Example from response of the `/metrics` endpoint:

```console
# HELP immudb_db_size_KB Database size in kilobytes.
# TYPE immudb_db_size_KB gauge
immudb_db_size_KB{db="cnlcdata"} 68
immudb_db_size_KB{db="cnlcinternalledger"} 36
immudb_db_size_KB{db="cnlcsyslogledger"} 36
immudb_db_size_KB{db="defaultdb"} 40
immudb_db_size_KB{db="lcledgeronekkgeln"} 108
immudb_db_size_KB{db="systemdb"} 36
```

2021-05-14 18:32 UTC, dmacvicar requested changes
As discussed in the team, we should follow the https://prometheus.io/docs/practices/naming/ recommendation:

>    ...should use base units (e.g. seconds, bytes, meters - not >milliseconds, megabytes, kilometers). See below for a list of base units.

2021-05-16 06:29 UTC, dmacvicar reviewed
I think leaving the size and entries method the same is ok. It was not the scope of the PR.

2021-05-16 08:38 UTC, padurean commented
This PR is now ready to be reviewed. Unfortunately the latest pushes didn't seem to trigger the GitHub workflows checks ...

2021-05-16 18:24 UTC, Hextar commented
I think the Server is still missing to add the "Access-Control-Allow-Origin" in the "Access-Control-Allow-Headers" to avoid receiving a CORS error from the browser.

2021-05-16 19:22 UTC, padurean commented
Weird. I could not reproduce the problem - i never new that the `Access-Control-Allow-Origin` (and `Access-Control-Allow-Methods`?) needs to be explicitly added to the value of `Access-Control-Allow-Headers`.
Of course, i could just add them. But i am not sure that it is really needed: i can not reproduce your error with Firefox 88.0.1 on Ubuntu. This is the script that i use in an html page that i load on one machine, requesting metrics from another machine:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
</head>
<body>
<script>
   fetch('http://192.168.1.247:9497/metrics')
     .then(data => { return data.text(); })
     .then(res => { console.log(res); })
     .catch(error => { throw(error); });
</script>
</body>
</html>
```

And in the browser console i can see the metrics - see screenshot - no CORS-related error.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/912518/118409785-d206ad00-b694-11eb-819e-ab758561d6fe.png">

If i then run it against the `master` branch of immudb (which does not have the CORS fix), it does throw a CORS error (second screenshot).
<img width="862" alt="image" src="https://user-images.githubusercontent.com/912518/118409862-29a51880-b695-11eb-9acb-548d9ce3455b.png">

I am curious why i can't reproduce ...

2021-05-16 19:28 UTC, Hextar commented
@padurean because firefox is more permissive on CORS. Is better to directly test on Chrome.

2021-05-16 19:40 UTC, padurean commented
@Hextar I've just tried with Chrome 90.0.4430.212 on Ubuntu, with the same script and i still can't reproduce it:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/912518/118410318-738efe00-b697-11eb-9105-f36385ab0f83.png">

And i was not able to find at least 1 CORS example which adds those `Access-Control-...` headers to the list of allowed headers ...

Does that HTML & JS that i pasted in my previous comment show the CORS error if you test with it?

2021-05-16 20:08 UTC, padurean commented
@Hextar I rewrote a bit the code so that only the needed headers and values are set on `OPTIONS` and `GET` methods.
I've still not added those 2 headers to the allowed headers header.
Lmk how it works (or not) for you with the latest changes.
If you still get those errors, i will just add the 2 headers to allowed headers.

2021-05-16 21:12 UTC, Hextar commented
@padurean using the .html I also have no problem fetching the resource, but even if it works with vanilla javascript, it could probably be something related to vue and/or axios (the dependecy used to interact with XHR).

I guess that I still need those 2 more headers if you could add them.

2021-05-16 21:41 UTC, padurean commented
@Hextar I've added them. Please retest.

2021-05-17 07:28 UTC, Hextar commented
@padurean I've tested your latest push and it was still saying that 'Access-Control-Allow-Credentials' was missing from the 'Access-Control-Allow-Headers'.

I've directly added it to the pkg/server/metrics.go file to avoid bothering you for just a string, and now it works!

Btw as far as I've understood those CORS errors happens only when running an node application

2021-05-17 07:37 UTC, padurean commented
@Hextar Alright. 👍

2021-05-17 07:43 UTC, dmacvicar commented
@Hextar I understand you added the missing headers in 8211525 and we can then merge this one?

2021-05-17 07:43 UTC, dmacvicar submitted a review, later dismissed

2021-05-17 08:39 UTC, dmacvicar approved these changes

2021-05-17 08:49 UTC, dmacvicar approved these changes

2021-05-17 08:50 UTC, merged